spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tguduru/ecommerce
eureka:
  client.serviceUrl.defaultZone: http://localhost:8761/eureka
  instance.hostname: config